use_frameworks!

target 'AFWebViewBrowser_Example' do
  pod 'AFWebViewBrowser', :path => '../'

  target 'AFWebViewBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
